review form
ArtemAstakhov/TechLeadersV pull request #112
Opened 2020-11-22 11:49 UTC by Fundorin174

Первый вариант формы отзыва. Пока не реализован datePicker, маска для телефона и скрол до ошибки. Еще добавлены сопутствующие изменения в страницу доктора и страницу с отзывами (вынес запрос отзывов на страницу отзывов.)  Также исправил маленький баг со слайдером на странице доктора. В моке отзыва нашел ошибку (в части отзывов не было названия организации, в которой было посещение врача)

2020-11-24 14:00 UTC, Fundorin174 commented
Добавлен весь требуемый функционал. Для реализации селекта по выбору клиник, создан mock clinics и внесены небольшие изменения в mock review.

2020-11-25 20:36 UTC, ArtemAstakhov requested changes

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/models/review.ts
> +  organization: Clinic;
я вот думаю, может ли быть кейс что ответ будет не из клиники,  которой оставили отзыв?
если нет, то зачем 2 клиники в модели?

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/pages/DoctorPage/index.tsx
> +                doctorFirstName={currentDoctor.firstName}
странно как то, почему бы просто не передать доктора туда?

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/pages/DoctorPage/index.tsx
> +    <ReviewsStoreProvider>
реально нужно ли оборачивать всю страницу, а не только reviews?

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/pages/ReviewFormPage/index.tsx
> +  useEffect(() => {
так вот че форма прыгает как бешенная, нужно это делать 1 раз после сабмита

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/store/ReviewStore.tsx
> +  reviews: ReviewsItem[] | null;
зачем null? чем пустой массив не устраивает?

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/store/ReviewStore.tsx
> +  const setReviews = React.useCallback((reviews: ReviewsItem[]) => {
судя по реализации функции - это addReviews, а не set

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/store/ReviewStore.tsx
> +import React from "react";
перенеси стор к странице

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/constants/estimatedParams.ts
> +    eng: "surveyThoroughness",
почему бы это не использовать как id?

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +          history.replace("/404");
как может быть 404 при запросе на ревьюс?

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +  const [reviewsFromProvider, setReviewsToProvider] = useReviewStore();
object destructuring!!!

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +  }, [reviewsFromProvider.reviews]);
чет не понятно
когда в провайдере меняются ревьюс, идет еще запрос за ревьюс и они устанавливаются в провайдер и затем идет бесконечный запрос за ревьюс?

аа, там же null то умолчанию...

все не так, тебе нужно инициализировать reviews внутри провайдера на didMount

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/pages/ReviewFormPage/Raitingstars/index.tsx
> +import React, { useState } from "react";
фигня какая то
я хочу компонент, чтобы я его вызвал в родителе так:

```
<Stars
  value={value}
  onChange={setValue}
  tooltips={RULES.map((r) => r.standartValue)}
/>
```

все, это компонент должен просто отображать звезды возвращать выбранное значение и отвечать за ховер только своих звезд и НЕ должен знать о какой либо бизнес логики в приложении

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/pages/ReviewFormPage/index.tsx
> +        setReviewsToProvider.setReviews([responseData]);
чет не арбайтен, было 5 ревьюс, добавил еще 1 и на странице доктора сейчас только 1

2020-11-25 20:36 UTC, ArtemAstakhov commented on src/pages/ReviewFormPage/index.tsx
> +  const [requaredParametrs, setRequaredParametr] = useState<string[]>([]);
вообще не понял этот проперти, где он устанавливается и зачем?

2020-11-26 11:00 UTC, Fundorin174 commented on src/models/review.ts
> +  organization: Clinic;
То есть organization оставляем, а из clinicAnswer убираем clinic чтоб не дублировать. Так?

2020-11-26 11:02 UTC, Fundorin174 commented on src/pages/DoctorPage/index.tsx
> +                doctorFirstName={currentDoctor.firstName}
Исправил. Думал, чем меньше передаем через пропсы, тем лучше... Там кроме имени ничего не нужно просто.

2020-11-26 11:11 UTC, Fundorin174 commented on src/pages/DoctorPage/index.tsx
> +    <ReviewsStoreProvider>
Исправил. Обернул Rewiews и RevewForm

2020-11-27 07:40 UTC, Fundorin174 commented on src/pages/DoctorPage/index.tsx
> +    <ReviewsStoreProvider>
Вернул назад. Только если мы оборачиваем всю страницу, в провайдер попадает и revews и reviewsForm, а они обе пользуются стором. Если создать два провайдера, то не работает.

2020-11-27 07:40 UTC, Fundorin174 commented on src/store/ReviewStore.tsx
> +  reviews: ReviewsItem[] | null;
исправил

2020-11-27 07:49 UTC, Fundorin174 commented on src/store/ReviewStore.tsx
> +  const setReviews = React.useCallback((reviews: ReviewsItem[]) => {
исправил

2020-11-27 07:51 UTC, Fundorin174 commented on src/store/ReviewStore.tsx
> +import React from "react";
готово

2020-11-27 08:04 UTC, Fundorin174 commented on src/constants/estimatedParams.ts
> +    eng: "surveyThoroughness",
сделал

2020-11-27 08:05 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +          history.replace("/404");
Убрал, оставить просто consol.error

2020-11-27 08:07 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +  const [reviewsFromProvider, setReviewsToProvider] = useReviewStore();
сделал

2020-11-27 08:07 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +  }, [reviewsFromProvider.reviews]);
сделал

2020-11-27 08:11 UTC, Fundorin174 commented on src/pages/ReviewFormPage/index.tsx
> +        setReviewsToProvider.setReviews([responseData]);
Вынос http запроса в провайдер решил, эту проблему. До этого отзывы сбрасывались, если обновить страницу во время добавления отзывов.

2020-11-27 08:17 UTC, Fundorin174 commented on src/models/review.ts
> +  organization: Clinic;
Исправил

2020-11-29 10:42 UTC, Fundorin174 commented on src/pages/ReviewFormPage/index.tsx
> +  useEffect(() => {
готово

2020-11-29 10:43 UTC, Fundorin174 commented on src/pages/ReviewFormPage/Raitingstars/index.tsx
> +import React, { useState } from "react";
готово. Но кроме этих проперти еще ID необходимо передать для работы toolTip

2020-11-29 10:44 UTC, Fundorin174 commented on src/pages/ReviewFormPage/index.tsx
> +  const [requaredParametrs, setRequaredParametr] = useState<string[]>([]);
Убрал, реализовал по нормальному через errors

2020-11-30 18:55 UTC, merged