Пока нет обработчиков событий. Для outlined стиля необходимо понимать…
ArtemAstakhov/TechLeadersV pull request #12
Opened 2020-10-04 08:00 UTC by profAlexGit

… какой будет фон, чтобы выглядело красиво

2020-10-04 14:10 UTC, ArtemAstakhov requested changes

2020-10-04 15:18 UTC, profAlexGit commented on src/ui/Input/types.ts
> +	variant?: EVariantInput;
Убрал интерфейсы

2020-10-04 15:19 UTC, profAlexGit commented on src/ui/Input/types.ts
> +	textType?: ETextType;
Хотел продемонстрировать как будет работать с ошибкой и предупреждением. Не очень хорошая была идея. Убрал этот интерфейс. Передаю error в props. Стили применяю в зависимости от наличия этого пропса

2020-10-04 15:19 UTC, profAlexGit commented on src/ui/Input/index.tsx
> +	placeholder="Введите...", ...props}) => {const classes = useStyles();
Убрал дефолтное значение

2020-10-04 15:20 UTC, profAlexGit commented on src/ui/Input/index.tsx
> +	placeholder="Введите...", ...props}) => {const classes = useStyles();
Исправил.

2020-10-05 19:31 UTC, ArtemAstakhov requested changes

2020-10-05 19:31 UTC, ArtemAstakhov commented on src/ui/Input/index.tsx
> +			{(placeholder || error) && (
не понятно, если написать плейсхолдер, то он появится и в инпуте и тут?
обычно это обособленное проперти tip

2020-10-05 19:31 UTC, ArtemAstakhov commented on src/ui/Input/index.tsx
> +				pattern="\S+.*"
общий компонент не должен отвечать за валидацию

2020-10-05 19:31 UTC, ArtemAstakhov commented on src/ui/Input/styles.jss.ts
> +		borderWidth: '1px',
просто 1

2020-10-05 19:31 UTC, ArtemAstakhov commented on src/ui/Input/styles.jss.ts
> +			borderRadius: '7px',
просто 7

2020-10-05 19:31 UTC, ArtemAstakhov commented on src/ui/Input/styles.jss.ts
> +			borderRadius: '7px',
!

2020-10-11 06:01 UTC, closed without merging

2020-10-11 06:01 UTC, ArtemAstakhov commented
merged with single commit