Modal window
ArtemAstakhov/TechLeadersV pull request #14
Opened 2020-10-04 13:39 UTC by Fundorin174

First commit by Dmitry Senkevich

2020-10-04 14:09 UTC, ArtemAstakhov requested changes

2020-10-04 14:25 UTC, Fundorin174 commented on src/ui/Modal/types.ts
> +  toggleModal?: () => void;
```suggestion
 export type ModalProps = {
  title?: string;
  open?: string | false;
  onClose?: () => void;
}
```

2020-10-04 14:28 UTC, Fundorin174 commented on src/ui/Modal/types.ts
> +  toggleModal?: () => void;
Исправлено

2020-10-04 14:28 UTC, Fundorin174 commented on src/ui/Modal/types.ts
> +  title?: string | undefined;
Исправлено

2020-10-04 14:28 UTC, Fundorin174 commented on src/ui/Modal/types.ts
> +  className?: string | false | undefined;
Исправлено

2020-10-04 14:28 UTC, Fundorin174 commented on src/ui/Modal/index.tsx
> +    <div className={clsx(classes.popup)}>
Исправлено

2020-10-04 14:29 UTC, Fundorin174 commented on .gitignore
> +package-lock.json
Исправлено, установил yarn

2020-10-04 14:30 UTC, Fundorin174 commented on src/ui/Modal/index.tsx
> +      <div className={clsx(classes.popupClose)} onClick = {props.toggleModal}>&times;
Ну да. Это спецсимвол крестика закрытия. Или надо рисунок обязательно? У этого цветом управлять можно

2020-10-04 14:30 UTC, Fundorin174 commented on src/ui/Modal/index.tsx
> +      <div className={clsx(classes.popupForm)}>
Исправлено

2020-10-04 14:30 UTC, Fundorin174 commented on src/ui/Modal/styles.jss.ts
> +    background: `url(${modalBackgroundImage}) top center no-repeat`,
исправлено

2020-10-05 18:46 UTC, ArtemAstakhov requested changes

2020-10-05 18:46 UTC, ArtemAstakhov commented on src/ui/Modal/styles.jss.ts
> +    webkitTransform: "translateX(-50%)",
jss умеет сам добавлять кроссбраузерные префиксы
просто transform достаточно

2020-10-05 18:46 UTC, ArtemAstakhov commented on src/ui/Modal/index.tsx
> +    <div className={clsx(classes.overlay, props.open)}>
нужно закрывать окно на клик в оверлей

2020-10-05 18:46 UTC, ArtemAstakhov commented on src/App.tsx
> +        open = {isModalVisible ? 'isVisible' : ''}
тут будет булеан open

2020-10-06 08:50 UTC, Fundorin174 commented on src/ui/Modal/types.ts
> +  open?: string | false;
done

2020-10-06 08:51 UTC, Fundorin174 commented on package-lock.json
> +{
done

2020-10-06 08:52 UTC, Fundorin174 commented on src/ui/Modal/styles.jss.ts
> +    webkitTransform: "translateX(-50%)",
done

2020-10-06 10:32 UTC, Fundorin174 commented on src/App.tsx
> +        open = {isModalVisible ? 'isVisible' : ''}
done

2020-10-06 13:05 UTC, Fundorin174 commented on src/ui/Modal/index.tsx
> +    <div className={clsx(classes.overlay, props.open)}>
done

2020-10-07 19:37 UTC, closed without merging

2020-10-07 19:37 UTC, ArtemAstakhov commented
Merged with single commit