added checkbox without styles
ArtemAstakhov/TechLeadersV pull request #15
Opened 2020-10-04 19:24 UTC by korytovaf

Не работал со стилями, так как пока не понимаю каким должен быть окончательный вид

2020-10-05 18:21 UTC, ArtemAstakhov requested changes

2020-10-05 18:21 UTC, ArtemAstakhov commented on src/ui/CheckBox/index.tsx
> +    const handler = useCallback(() => {
странная конструкция, setCheck((prev) => !prev) вполне достаточно

2020-10-05 18:21 UTC, ArtemAstakhov commented on src/ui/CheckBox/index.tsx
> +                <input name={name} id={name} type="checkbox" checked={check} onChange={handler}/>
а как компонент возвращает состояние родительскому, если handler просто меняет локальный стейт

2020-10-05 18:21 UTC, ArtemAstakhov commented on src/ui/CheckBox/index.tsx
> +            <label className={clsx(classes.root, {}, className)}>
что за пустой объект?

2020-10-05 18:21 UTC, ArtemAstakhov commented on src/ui/CheckBox/index.tsx
> +                <span>{label}</span>
по клику в лейбл тоже должен меняться стейт

2020-10-08 09:25 UTC, korytovaf commented
Поправил и добавил стили

2020-10-11 06:06 UTC, closed without merging

2020-10-11 06:06 UTC, ArtemAstakhov commented
merged with single commit