Kolesnikov auth form
ArtemAstakhov/TechLeadersV pull request #53
Opened 2020-10-17 07:56 UTC by Chutka

2020-10-17 19:33 UTC, ArtemAstakhov requested changes

2020-10-17 19:33 UTC, ArtemAstakhov commented on src/components/RegistrationForm/actions.ts
> +mock.onPost("/user/signup").reply(200, {
mock принимает функцию
сделай ответ через функцию, нужно условно отдавать либо успешный ответ либо ошибки с 401 статусом
в форме лови ошибки и устанавливай их в нужные поля

2020-10-17 19:33 UTC, ArtemAstakhov commented on src/components/LoginForm/actions.ts
> +    if (response.status) {
что то странное условие, если реквест не успешный, он вернет ответ с кодом ошибки

2020-10-17 19:33 UTC, ArtemAstakhov commented on src/components/LoginForm/actions.ts
> +    return Promise.reject(e);
установить ошибки в форму

2020-10-17 19:33 UTC, ArtemAstakhov commented on src/components/LoginForm/index.tsx
> +    login(data)
async await

2020-10-17 19:33 UTC, ArtemAstakhov commented on src/components/RegistrationForm/index.tsx
> +      <Input
сделай через Controller

2020-10-17 19:33 UTC, ArtemAstakhov commented on src/models/dataModel.ts
> +export interface IDataModel<T> {
нужен ли этот объект?

2020-10-17 19:33 UTC, ArtemAstakhov commented on src/store/AppStore.tsx
> +  user?: IUserModel,
в UserStore

2020-10-22 20:12 UTC, Chutka commented on src/store/AppStore.tsx
> +  user?: IUserModel,
Сделал

2020-10-22 20:13 UTC, Chutka commented on src/models/dataModel.ts
> +export interface IDataModel<T> {
Убрал, думаю лишнее

2020-10-22 20:13 UTC, Chutka commented on src/components/RegistrationForm/index.tsx
> +      <Input
Все формы переделал

2020-10-22 20:13 UTC, Chutka commented on src/components/LoginForm/index.tsx
> +    login(data)
Сделал

2020-10-22 20:13 UTC, Chutka commented on src/components/LoginForm/actions.ts
> +    return Promise.reject(e);
Вот тут не очень понял
Можешь пример плиз привести

2020-10-22 20:14 UTC, Chutka commented on src/components/LoginForm/actions.ts
> +    if (response.status) {
Убрал модельку (DataModel), от условий тоже избавился

2020-10-24 09:43 UTC, Chutka commented on src/components/RegistrationForm/actions.ts
> +mock.onPost("/user/signup").reply(200, {
Сделал для всех форм

2020-10-24 09:45 UTC, Chutka commented on src/components/RegistrationForm/actions.ts
> +mock.onPost("/user/signup").reply(200, {
не оч понял идею с отлавливанием для полей: Получается чтобы при ошибке типо такого ответ чтобы был?
```
return [
  400,
  {
    email: "Не верное значение",
    password: "Недопустимые символы",
  },
]
```

2020-10-28 19:32 UTC, Chutka commented on src/components/RegistrationForm/actions.ts
> +mock.onPost("/user/signup").reply(200, {
Добавил модель, так что думаю можно вливать. По ответу от бека теперь будут отображаться ошибки к соответствующим полям

2020-10-28 19:32 UTC, Chutka commented on src/components/LoginForm/actions.ts
> +    return Promise.reject(e);
Сделал

2020-11-04 08:26 UTC, merged