Kolesnikov modal revision
ArtemAstakhov/TechLeadersV pull request #74
Opened 2020-10-31 09:49 UTC by Chutka

2020-10-31 15:23 UTC, ArtemAstakhov requested changes

2020-10-31 15:23 UTC, ArtemAstakhov commented on src/pages/MainPage/index.tsx
> +  const [isModalOpened, setIsModalOpened] = useState(false);
перенести пример в сторибук

2020-10-31 15:23 UTC, ArtemAstakhov commented on src/ui/Modal/styles.jss.ts
> +  styles as any,
добавь as any к медиа запросу в popup классе, где проблема, а то если добавлять на все стили, то в компонента пропадут проперти у объекта

2020-10-31 15:23 UTC, ArtemAstakhov commented on src/ui/Modal/index.tsx
> +  const handlePopupClick = useCallback((e: SyntheticEvent<HTMLDivElement>) => {
это что?

2020-10-31 15:23 UTC, ArtemAstakhov commented on public/index.html
> +    <div id="modal"></div>
это в каждом проекте, где используется эта модалка нужно создавать под нее якорь?

2020-10-31 15:23 UTC, ArtemAstakhov commented on public/index.html
> +    <div id="modal"></div>
если не будет идеи - пиши, покажу как сделать

2020-11-04 18:38 UTC, Chutka commented on public/index.html
> +    <div id="modal"></div>
document.body использовать ?

2020-11-07 07:19 UTC, ArtemAstakhov commented on public/index.html
> +    <div id="modal"></div>
да, напрямую в конец body

2020-11-21 20:48 UTC, merged