doctor page and page 404
ArtemAstakhov/TechLeadersV pull request #78
Opened 2020-11-01 13:53 UTC by Fundorin174

2020-11-03 06:58 UTC, ArtemAstakhov requested changes

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/styles.jss.ts
> +  col: {},
реально ли нужны эти jss классы? или можно обойтись обычными?

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/WorkExperience/index.tsx
> +        {props.currentDoctor?.about.workExperience.map((organization) => {
дестракшн

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Shedule/index.tsx
> +        {props.currentDoctor?.about.schedule.map((organization) => {
дестракшн
у тебя же doctor обязательное проперти, зачем элвис?

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Gallery/index.tsx
> +const Gallery: React.FC<PropsType> = (props: PropsType) => {
дестракшн

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Gallery/index.tsx
> +        {props.currentDoctor?.about.gallery.map((photo, i) => {
элвис?

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Education/index.tsx
> +const Education: React.FC<PropsType> = (props: PropsType) => {
дустракшн

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Description/index.tsx
> +  props: DescriptionPropsType
дестракшн

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Description/index.tsx
> +    props.reviews.map((review) => {
как работает map? в чем отличие от forEach?

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +const Reviews: React.FC<PropsType> = (props: PropsType) => {
дестракшн

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +  let standartrules: MarkTostringRule[] = [
вынести в папку constants, смотри там есть пример

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +      let newPageData = sortedReviews?.slice(startRow, finishRow);
у тебя sortedReview не могут быть null или undefined, зачем элвис? я так понимаю это элвис вынушдает чуть ниже делать приведение типов

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +      const values = Object.values(review.estimation);
используй лодаш

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +  const renderingRevies = !useAppStore()[0].device.isMobile
ох жесть, используй вызов стейта в начале

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +    const values = Object.values(review.estimation);
лодаш

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +    const commonRaiting = +(
если у тебя там массив чисел, зачем этот плюс?

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +    const raiting = +commonRaiting.toFixed(0);
ты выше уже получил точно число, зачем этот плюс?

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/index.tsx
> +  if (!useAppStore()[0].device.isMobile)
omgadble

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/Review/index.tsx
> +const Review: React.FC<ReviewsPropsType> = (props: ReviewsPropsType) => {
дестракшен

2020-11-03 06:58 UTC, ArtemAstakhov commented on src/pages/DoctorPage/Reviews/Review/index.tsx
> +  let adviseRules: MarkTostringRule[] = [
в константы

2020-11-03 10:33 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +    const raiting = +commonRaiting.toFixed(0);
Метод toFixed возвращает строку.

2020-11-03 10:52 UTC, Fundorin174 commented on src/pages/ListOfDoctors/index.tsx
> +        url: `/doctors`,
done

2020-11-03 10:53 UTC, Fundorin174 commented on src/pages/ListOfDoctors/index.tsx
> +          url: `/doctors`,
done

2020-11-03 10:55 UTC, Fundorin174 commented on src/pages/ListOfDoctors/index.tsx
> +    const response = await HttpService.get<Doctor[]>(`/doctors`);
done

2020-11-03 10:59 UTC, Fundorin174 commented on src/pages/DoctorPage/types.ts
> +export type ReviewsItem = {
Done

2020-11-03 11:40 UTC, Fundorin174 commented on src/models/doctor.ts
> +  age: number;
done

2020-11-03 12:19 UTC, Fundorin174 commented on src/models/doctor.ts
> +    category: string;
done

2020-11-03 12:19 UTC, Fundorin174 commented on src/models/doctor.ts
> +    degree?: string;
done

2020-11-03 12:22 UTC, Fundorin174 commented on src/models/doctor.ts
> +type EducationItem = {
done

2020-11-03 12:22 UTC, Fundorin174 commented on src/models/doctor.ts
> +type WorkExperienceItem = {
done

2020-11-03 12:23 UTC, Fundorin174 commented on src/models/doctor.ts
> +type ScheduleItem = {
done

2020-11-03 12:24 UTC, Fundorin174 commented on src/models/doctor.ts
> +type WorkingTimeType = {
done

2020-11-03 14:46 UTC, Fundorin174 commented on src/models/doctor.ts
> +  studyDuration: string;
Done + вынес функцию getWorkTime в helpers и сделал ее универсальной. В связи с этим чуть исправил ListOfDoctors

2020-11-03 15:10 UTC, Fundorin174 commented on src/models/doctor.ts
> +  day: string;
done

2020-11-04 08:28 UTC, Fundorin174 commented on src/models/doctor.ts
> +  time: string;
done

2020-11-04 08:37 UTC, Fundorin174 commented on src/models/review.ts
> +    dateOfAnswer: string;
done

2020-11-04 08:38 UTC, Fundorin174 commented on src/models/review.ts
> +    answerText: string;
done

2020-11-04 09:05 UTC, Fundorin174 commented on src/assets/images/addr_pin.svg
> +<svg width="12" height="13" viewBox="0 0 12 13" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2020-11-04 09:57 UTC, Fundorin174 commented on src/pages/DoctorPage/index.tsx
> +        .then((response) => {
done

2020-11-04 10:00 UTC, Fundorin174 commented on src/pages/DoctorPage/index.tsx
> +  if (currentDoctor && reviews)
done

2020-11-04 10:01 UTC, Fundorin174 commented on src/pages/DoctorPage/index.tsx
> +  let { doctorID } = useParams<IParams>();
done

2020-11-04 10:02 UTC, Fundorin174 commented on src/pages/DoctorPage/index.tsx
> +            {currentDoctor &&
done

2020-11-04 10:03 UTC, Fundorin174 commented on src/pages/DoctorPage/WorkExperience/index.tsx
> +        {props.currentDoctor?.about.workExperience.map((organization) => {
done

2020-11-04 10:04 UTC, Fundorin174 commented on src/pages/DoctorPage/Gallery/index.tsx
> +const Gallery: React.FC<PropsType> = (props: PropsType) => {
done

2020-11-04 10:04 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/Review/index.tsx
> +const Review: React.FC<ReviewsPropsType> = (props: ReviewsPropsType) => {
done

2020-11-04 10:12 UTC, Fundorin174 commented on src/pages/DoctorPage/Gallery/index.tsx
> +        {props.currentDoctor?.about.gallery.map((photo, i) => {
remove

2020-11-04 10:27 UTC, Fundorin174 commented on src/pages/DoctorPage/Education/index.tsx
> +const Education: React.FC<PropsType> = (props: PropsType) => {
done

2020-11-04 11:02 UTC, Fundorin174 commented on src/pages/DoctorPage/Description/index.tsx
> +    props.reviews.map((review) => {
Map возвращает новый массив, а нам тут ничего возвращать не нужно. Поменял

2020-11-04 11:02 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +const Reviews: React.FC<PropsType> = (props: PropsType) => {
done

2020-11-04 13:17 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +  let standartrules: MarkTostringRule[] = [
done, исчез смысл в функции MarkToString, удалил

2020-11-04 13:23 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +      let newPageData = sortedReviews?.slice(startRow, finishRow);
Убрал, странно. Точно помню что в начале без этих элвисов ошибку выдавал. Наверно потому, что я вначале не задавал начальное значение [].

2020-11-04 13:38 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +      const values = Object.values(review.estimation);
done

2020-11-04 13:58 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +    const values = Object.values(review.estimation);
done

2020-11-04 13:58 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +    const commonRaiting = +(
done in lodash

2020-11-04 13:58 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +    const raiting = +commonRaiting.toFixed(0);
done in lodash

2020-11-04 13:59 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/Review/index.tsx
> +  let adviseRules: MarkTostringRule[] = [
done

2020-11-04 14:02 UTC, Fundorin174 commented on src/pages/DoctorPage/Shedule/index.tsx
> +        {props.currentDoctor?.about.schedule.map((organization) => {
done

2020-11-04 17:44 UTC, Fundorin174 commented on src/pages/DoctorPage/styles.jss.ts
> +  col: {},
убрал ненужное. Был мусор.

2020-11-04 17:54 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +  if (!useAppStore()[0].device.isMobile)
Done

2020-11-04 17:55 UTC, Fundorin174 commented on src/pages/DoctorPage/Reviews/index.tsx
> +  const renderingRevies = !useAppStore()[0].device.isMobile
done

2020-11-05 08:35 UTC, Fundorin174 commented on src/assets/images/addr_pin.svg
> +<svg width="12" height="13" viewBox="0 0 12 13" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2020-11-07 07:16 UTC, merged